routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view ('auth.login');
});

Route::get('/logout', 'Auth\LoginController@logout');
Auth::routes();

Route::match(['get', 'post'], '/register', function () {
  return redirect("/login");
})->name("register"); //Agar ketika halaman register di akses akan otomatis dialihkan ke halaman login

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile/{id}', 'UserController@showProfile')->name('profile');
Route::put('/profile', 'UserController@updateProfile')->name('profile.update');
Route::resource('users', 'UserController');


Route::resource('jabatans', 'JabatanController');

app/Jabatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class JabatanController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
		$jabatans = \App\Jabatan::paginate(10);

    return view ('jabatans.index', ['jabatans' => $jabatans]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('jabatans.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
		$new_jabatan = new \App\Jabatan;
		
		$new_jabatan->name = $request->get('name');
		$new_jabatan->keterangan = $request->get('keterangan');
		$new_jabatan->gaji = $request->get('gaji');

		$new_jabatan->created_by = \Auth::user()->id;

		$new_jabatan->save();

		return redirect()->route('jabatans.create')->with('status', 'Data jabatan berhasil disimpan');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $jabatan = \App\Jabatan::findOrFail($id);

    return view('jabatans.edit', ['jabatan' => $jabatan]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $jabatan = \App\Jabatan::findOrFail($id);
		
		$jabatan->name = $request->get('name');
		$jabatan->keterangan = $request->get('keterangan');
		$jabatan->gaji = $request->get('gaji');

		$jabatan->updated_by = \Auth::user()->id;

		$jabatan->save();

		return redirect()->route('jabatans.edit', [$jabatan->id])->with('status', 'Data jabatan berhasil diedit');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
		$jabatan = \App\Jabatan::findOrFail($id);
		$jabatan->delete();

		return redirect()->route('jabatans.index')->with('status', 'Jabatan berhasil dihapus');

  }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $users = \App\User::paginate(10);

    return view('users.index', ['users' => $users]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('users.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    //
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
		$user = \App\User::findOrFail($id);
		
		return view('users.show', ['user' => $user]);
	}
	
	public function showProfile($id)
	{
		$user = \App\User::findOrFail($id);
		
		return view('users.show_profile', ['user' => $user]);
	}

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    //
	}

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    //
	}
	
	public function updateProfile(Request $request)
  {
    $id = \Auth::user()->id;

    $user = \App\User::findOrFail($id);
    $user->tempat_tinggal = $request->get('tempat_tinggal');
    $user->status_perkawinan = $request->get('status_perkawinan');
    $user->jenis_kelamin = $request->get('jenis_kelamin');
    $user->jumlah_anak = $request->get('jumlah_anak');
    $user->email = $request->get('email');
    $user->telepon = $request->get('telepon');
    $user->pendidikan_terakhir = strtoupper($request->get('pendidikan_terakhir'));
    $user->jurusan_pendidikan_terakhir = strtoupper($request->get('jurusan_pendidikan_terakhir'));

    $user->save();

    return redirect()->route('profile', $id)->with('status', 'Data berhasil di update');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    //
  }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('title')
  Dashboard
@endsection

@section('content')
   <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Sistem Informasi Kepegawaian (SISIPEG)</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item active">Dashboard</div>
            </div>
          </div>

          <div class="section-body">
            <h2 class="section-title">Selamat datang di menu Dashboard, Admin !</h2>
              <p class="section-lead">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
              </p>
              
              <!-- Your content goes here -->

              <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div class="card card-statistic-1">
                    <div class="card-icon bg-primary">
                      <i class="far fa-user"></i>
                    </div>
                    <div class="card-wrap">
                      <div class="card-header">
                        <h4>Total Admin</h4>
                      </div>
                      <div class="card-body">
                        2
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div class="card card-statistic-1">
                    <div class="card-icon bg-success">
                      <i class="far fa-user"></i>
                    </div>
                    <div class="card-wrap">
                      <div class="card-header">
                        <h4>Total Pegawai</h4>
                      </div>
                      <div class="card-body">
                        10
                      </div>
                    </div>
                  </div>
                </div>

                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div class="card card-statistic-1">
                    <div class="card-icon bg-warning">
                      <i class="far fa-file"></i>
                    </div>
                    <div class="card-wrap">
                      <div class="card-header">
                        <h4>Pengajuan Cuti</h4>
                      </div>
                      <div class="card-body">
                        4
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div class="card card-statistic-1">
                    <div class="card-icon bg-success">
                      <i class="fas fa-circle"></i>
                    </div>
                    <div class="card-wrap">
                      <div class="card-header">
                        <h4>Mutasi Rayon</h4>
                      </div>
                      <div class="card-body">
                        47
                      </div>
                    </div>
                  </div>
                </div>
              </div>



              <div class="card">
                <div class="card-header">
                  <h4>Example Card</h4>
                </div>

                <div class="card-body">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>

                <div class="card-footer bg-whitesmoke">
                  This is card footer
                </div>
              </div>
            
          </div>
        </section>
      </div>
@endsection

resources/views/jabatans/create.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Pegawai
@endsection

@section('content')
  <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{route('jabatans.index')}}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Tambah Data Jabatan</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="{{route('jabatans.index')}}">Jabatan</div></a>
              <div class="breadcrumb-item active">Tambah Data Jabatan</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Silahkan isi data-data berikut ini</h4><br><br>
                  </div>

                  

                  <form
                    action="{{route('jabatans.store')}}"
                    method="POST">
                  
                    @csrf

                    <div class="card-body">
                      
                      @if(session('status'))
                      <div class="alert alert-success alert-dismissible show fade">
                        <div class="alert-body">
                          <button class="close" data-dismiss="alert">
                            <span>×</span>
                          </button>
                          {{session('status')}}
                        </div>
                      </div>
                      @endif

                      <div class="form-group">
                        <label for="name">Nama Jabatan / Divisi</label>
                        <input type="text" class="form-control" required="" name="name">
                      </div>
                      <div class="form-group">
                        <label for="keterangan">Keterangan</label>
                        <textarea class="form-control" name="keterangan" id="keterangan"" required></textarea>
                      </div>
                      <div class="form-group mb-0">
                        <label for="">Gaji (Rp.)</label>
                        <input type="number" name="gaji" class="form-control" required>
                      </div>
                    </div>

                    <div class="card-footer text-right">
                      <button class="btn btn-primary">Simpan</button>
                    </div>

                  </form>
 
                </div>
              </div>
            </div>
          </div>

        </section>
      </div>
@endsection

resources/views/jabatans/edit.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Pegawai
@endsection

@section('content')
  <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{route('jabatans.index')}}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Edit Data Jabatan</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="{{route('jabatans.index')}}">Jabatan</div></a>
              <div class="breadcrumb-item active">Edit Data Jabatan</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Silahkan edit data jabatan berikut ini</h4><br><br>
                  </div>

                  <form
                    action="{{route('jabatans.update', [$jabatan->id])}}"
                    method="POST">
                  
                    @csrf

                    <input
                      type="hidden"
                      name="_method"
                      value="PUT">

                    <div class="card-body">
                      
                      @if(session('status'))
                      <div class="alert alert-success alert-dismissible show fade">
                        <div class="alert-body">
                          <button class="close" data-dismiss="alert">
                            <span>×</span>
                          </button>
                          {{session('status')}}
                        </div>
                      </div>
                      @endif

                      <div class="form-group">
                        <label for="name">Nama Jabatan / Divisi</label>
                        <input 
                          type="text" 
                          class="form-control" 
                          required 
                          name="name" 
                          value="{{old('name') ? old('name') : $jabatan->name}}">
                      </div>
                      <div class="form-group">
                        <label for="keterangan">Keterangan</label>
                        <textarea class="form-control" name="keterangan" id="keterangan"" required>{{{old('keterangan') ? old('keterangan') : $jabatan->keterangan}}}</textarea>
                      </div>
                      <div class="form-group mb-0">
                        <label for="">Gaji (Rp.)</label>
                        <input 
                          type="number" 
                          name="gaji" 
                          class="form-control" 
                          required
                          value="{{old('gaji') ? old('gaji') : $jabatan->gaji}}">
                      </div>
                    </div>

                    <div class="card-footer text-right">
                      <button class="btn btn-primary">Simpan</button>
                    </div>

                  </form>
 
                </div>
              </div>
            </div>
          </div>

        </section>
      </div>
@endsection

resources/views/jabatans/index.blade.php
@extends('layouts.app')

@section('title')
  Data Pegawai
@endsection

@section('content')
  <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Daftar Jabatan</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb-item active">Data Jabatan</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
              
                @if(count($jabatans)>0)
                  <div class="card">
                    <div class="card-header">
                    <h4>Tabel Habatan</h4><br><br>
                      </div>

                      <div class="card-header">
                      
                        <a href="{{route('jabatans.create')}}" class="btn btn-icon icon-left btn-primary btn-sm">
                          <i class="far fa-edit"></i> Tambah data
                        </a>
                        
                      </div>

                    <div class="card-body">

                      @if(session('status'))
                      <div class="alert alert-success alert-dismissible show fade">
                        <div class="alert-body">
                          <button class="close" data-dismiss="alert">
                            <span>×</span>
                          </button>
                          {{session('status')}}
                        </div>
                      </div>
                      @endif

                      <div class="table-responsive">
                        <table class="table table-striped table-md">
                          <tbody><tr>
                            <th>ID</th>
                            <th>Nama Jabatan</th>
                            <th>Deskripsi / Keterangan</th>
                            <th>Gaji</th>
                            <th>Action</th>
                          </tr>

                          @foreach($jabatans as $jabatan)
                          <tr>
                            <td>{{$jabatan->id}}</td>
                            <td>{{$jabatan->name}}</td>
                            <td>{{$jabatan->keterangan}}</td>
                            <td>{{$jabatan->gaji}}</td>
    
                            <td>
                              <a href="{{route('jabatans.edit', [$jabatan->id])}}" class="btn btn-success btn-sm">Edit</a>

                              <form 
                                onsubmit="return confirm('Hapus jabatan ini secara permanen?')"
                                class="d-inline"
                                action="{{route('jabatans.destroy', [$jabatan->id])}}"
                                method="POST"
                                >

                                @csrf

                                <input type="hidden" name="_method" value="DELETE">
                                <input type="submit" value="Delete" class="btn btn-danger btn-sm"></input>
                              </form>
                                
                            </td>

                          </tr>
                          @endforeach
                          </tbody>

                          <tfoot>
                            <tr>
                              <td colspan="10">
                                {{$jabatans->links()}}
                                
                                <!-- {{$jabatans->appends(Request::all())->links()}} -->
                              </td>
                            </tr>
                          </tfoot>
                          
                        </table>
                      </div>
                    </div>

                    {{-- <div class="card-footer text-right">
                      <nav class="d-inline-block">
                        <ul class="pagination mb-0">
                          <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1"><i class="fas fa-chevron-left"></i></a>
                          </li>
                          <li class="page-item active"><a class="page-link" href="#">1 <span class="sr-only">(current)</span></a></li>
                          <li class="page-item">
                            <a class="page-link" href="#">2</a>
                          </li>
                          <li class="page-item"><a class="page-link" href="#">3</a></li>
                          <li class="page-item">
                            <a class="page-link" href="#"><i class="fas fa-chevron-right"></i></a>
                          </li>
                        </ul>
                      </nav>
                    </div> --}}

                  </div>
                  
                @else
                  <div class="card">
                    <div class="card-header">
                      <h4>Data Masih Kosong</h4>
                    </div>
                    <div class="card-body">
                      <div class="empty-state" data-height="400" style="height: 400px;">
                        <div class="empty-state-icon">
                          <i class="fas fa-question"></i>
                        </div>
                        <h2>Tidak ada data yang ditemukan</h2>
                        <p class="lead">
                          Mohon maaf, silahkan isi data terlebih dahulu
                        </p>
                        <a href="{{route('jabatans.create')}}" class="btn btn-primary mt-4">Isi Data</a>
                      </div>
                    </div>
                  </div>
                @endif

            
              </div>
            </div>
          </div>

        </section>
      </div>
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title')
  Tambah Data Pegawai
@endsection

@section('content')
  <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <div class="section-header-back">
              <a href="{{route('users.index')}}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Tambah Data Pegawai / Users</h1>
            <div class="section-header-breadcrumb">
              <div class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></div>
              <div class="breadcrumb-item"><a href="{{route('users.index')}}">Pegawai</div></a>
              <div class="breadcrumb-item active">Tambah Data Pegawai</div>
            </div>
          </div>

          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Silahkan isi data-data berikut ini</h4><br><br>
                  </div>

                  <form
                    action="{{route('users.store')}}"
                    method="POST"
                    enctype="multipart/form-data">
                  
                    @csrf

                    <div class="card-body">
                      
                      @if(session('status'))
                      <div class="alert alert-success alert-dismissible show fade">
                        <div class="alert-body">
                          <button class="close" data-dismiss="alert">
                            <span>×</span>
                          </button>
                          {{session('status')}}
                        </div>
                      </div>
                      @endif

                      <div class="form-group">
                        <label for="name">Nama Pegawai</label>
                        <input type="text" class="form-control" required="" name="name" value="">
                      </div>

                      <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" required="" name="username" value="">
                      </div>

                      <div class="form-group">
                        <label for="foto">Pas Foto</label>
                        <input 
                          type="file" 
                          class="form-control" 
                          required="" 
                          name="foto" 
                          value="">
                      </div>

                      <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" required="" name="email" value="" placeholder="user@email.com">
                      </div>

                      <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" required="" name="password" value="" placeholder="password">
                      </div>

                      <div class="form-group">
                        <label for="roles">Roles Akun</label>
                        <div class="selectgroup selectgroup-pills">
                          <label class="selectgroup-item">
                            <input 
                              type="checkbox" 
                              name="roles[]" 
                              value="ADMIN" 
                              class="selectgroup-input"
                              id="ADMIN" 
                              required>
                            <span class="selectgroup-button">ADMIN</span>
                          </label>

                          <label class="selectgroup-item">
                            <input 
                              type="checkbox" 
                              name="roles[]" 
                              value="PEGAWAI" 
                              class="selectgroup-input"
                              id="PEGAWAI" 
                              required>
                            <span class="selectgroup-button">PEGAWAI</span>
                          </label>

                          <label class="selectgroup-item">
                            <input 
                              type="checkbox" 
                              name="roles[]" 
                              value="DIREKTUR" 
                              class="selectgroup-input"
                              id="DIREKTUR" 
                              required>
                            <span class="selectgroup-button">DIREKTUR</span>
                          </label>
                        </div>

                      </div>

                      <div class="form-group">
                        <label for="tempat_lahir">Tempat Lahir</label>
                        <input type="text" class="form-control" required="" name="tempat_lahir" value="">
                      </div>

                      <div class="form-group">
                        <label for="tanggal_lahir">Tanggal Lahir</label>
                        <input type="date" class="form-control" required="" name="tanggal_lahir" value="">
                      </div>

                      <div class="form-group">
                        <label for="jenis_kelamin">Jenis Kelamin</label>
                          <div class="custom-switches-stacked mt-2">
                            <label class="custom-switch">
                              <input type="radio" name="jenis_kelamin" value="PRIA" class="custom-switch-input" checked="" required>
                              <span class="custom-switch-indicator"></span>
                              <span class="custom-switch-description">PRIA</span>
                            </label>
                            <label class="custom-switch">
                              <input type="radio" name="jenis_kelamin" value="WANITA" class="custom-switch-input" checked="" required>
                              <span class="custom-switch-indicator"></span>
                              <span class="custom-switch-description">WANITA</span>
                            </label>
                          </div>
                      </div>

                      <div class="form-group">
                        <label for="tempat_tinggal">Tempat Tinggal Saat Ini</label>
                        <textarea class="form-control" name="tempat_tinggal id="keterangan"" required></textarea>
                      </div>

                      <div class="form-group">
                        <label for="NIK">NIK</label>
                        <input type="number" name="nik" class="form-control" required>
                      </div>

                      <div class="form-group">
                        <label for="keterangan">Keterangan</label>
                        <textarea class="form-control" name="keterangan" id="keterangan"" required></textarea>
                      </div>


              
                    </div>

                    <div class="card-footer text-right">
                      <button class="btn btn-primary">Simpan</button>
                    </div>

                  </form>

                </div>
              </>
            </div>
          </div>

        </section>
      </div>
@endsection